// Top-level build file where you can add configuration options common to all sub-projects/modules.

plugins {
    id 'com.android.application' version '8.5.0' apply false
}

// Gradle constants defined at root level
ext {
    // Google Play SDK version requirements:
    // https://support.google.com/googleplay/android-developer/answer/11926878
    compileSdkVersion = 35
    buildToolsVersion = "35.0.0"
    minSdkVersion = 14
    targetSdkVersion = 35
    espressoCoreVersion = 'androidx.test.espresso:espresso-core:3.5.1'
    junitVersion = 'junit:junit:4.13.2'
    robolectricVersion = 'org.robolectric:robolectric:4.10.3'
    // androidx migration:
    // https://developer.android.com/jetpack/androidx/migrate
    // https://developer.android.com/jetpack/androidx/migrate/artifact-mappings
    appCompatXVersion = 'androidx.appcompat:appcompat:1.6.1'
    constraintXVersion = 'androidx.constraintlayout:constraintlayout:2.1.4'
    supportXVersion = 'androidx.legacy:legacy-support-v4:1.0.0'
    leanbackCompatXVersion = 'androidx.leanback:leanback:1.1.0-alpha02'
    designXVersion = 'com.google.android.material:material:1.9.0'
    voiceOverlayVersion = 'com.algolia.instantsearch:voice:1.1.0'
}

gradle.projectsEvaluated {
    tasks.withType(JavaCompile) {
        options.compilerArgs << "-Xlint:unchecked" << "-Xlint:deprecation"
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
